### ISSUE TITLE
Installation info for newbies

### ISSUE THREAD

**Issue by Rikkiff** [jakobnissen/alen#11]
Hi Jakob, 

I am missing information on how to install alen. I have downloaded to compressed file to my download folder (I am running Windows subsystem for Linux) and uncompressed it. So, where do I put the files then? 

Best, 
Rikki

**Comment by jakobnissen** [comment]
Dear @Rikkiff 

You have two options:
* Download the file ` alen-v0.3.1-linux-amd64.zip`, and uncompress it. You can then run the file `bin/alen` directly.
* Clone this repository. Then install Rust, and compile it yourself by running `cargo build --release`. You can then find the binary in `targets/release/alen`

Closing as solved. Please let me know if you need more help.

**Comment by Rikkiff** [comment]
Thanks Jokab!

It works brilliantly. 

Best
