### ISSUE TITLE
Implement CI with GitHub Actions

### ISSUE THREAD

**Issue by jhwgh1968** [jakobnissen/alen#2]
## Steps

- [x] PR job which runs a build, `rustfmt`, and `clippy`
- [x] Master build job with status badge in `README.md`
- [x] New release job, which builds a Changelog from commit history and opens a draft release
- [x] New release job attaches pre-built binaries for Linux
- [x] New release job attaches pre-built binaries for MacOS (x86_64)

---
I'm a big believer that every open source project destined for success must make contributions (and maintenance) easy. A solid CI is a cornerstone of that.

If you can spare a week or two, I'd offer to do this for you.

**Comment by jakobnissen** [comment]
That looks amazing! I'd been wantng to do something like this, but this being my first Rust package, I'm not sure how to. If you would make some PRs implementing this, I'd gladly accept it.

**Comment by jhwgh1968** [comment]
As I work on a Draft Release job, a question: what matrix of binary releases do you want?

I am currently working on x86_64 Linux. What about Windows, and what about other platforms (e.g. ARM)? I have no idea what hardware Bioinformatics is done on these days, but it sounds very expensive. :smile:

**Comment by jakobnissen** [comment]
Bioinformaticians nearly exclusively use x86_64 Linux and MacOS. I guess having a Windows release would be nice as well, just in case. Is it possible to compile native binaries for the new ARM-based Macs? I think that's the only situtation people wouldn't use x86_64 Windows/Linux/MacOS

**Comment by jhwgh1968** [comment]
> Is it possible to compile native binaries for the new ARM-based Macs?

Unfortunately GitHub Actions does not have runners for those yet. Once they do, hopefully it will be easy to copy-paste the MacOS job I'll write.

**Comment by jakobnissen** [comment]
Okay. Native binaries for ARM-based macs can wait, I hear the x86 emulation software works very well. And I'm also pretty sure the terminal's rendering is the bottleneck for Alen, for all practical purposes.

Thanks for doing this, again. I can also use your PRs as a template for any future command-line tool I build in Rust ❤️

**Comment by jakobnissen** [comment]
@jhwgh1968 Just tell me if I need to do anything, and/or when I can give it a try and make a new release, such that the binaries are created.

**Comment by jhwgh1968** [comment]
I just updated the issue, things should be ready to go!

**Comment by jakobnissen** [comment]
Perfect!
